# Generated by Django 5.2.6 on 2025-09-19 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='unique_order_id',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
